/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Form: typeof import('./../../../src/components/king-form/form-render/form.vue')['default']
    FormField: typeof import('./../../../src/components/king-form/form-render/form-field.vue')['default']
    FormLabel: typeof import('./../../../src/components/king-form/form-render/form-label.vue')['default']
    FormMessage: typeof import('./../../../src/components/king-form/form-render/form-message.vue')['default']
    KingLayout: typeof import('./../../../src/components/king-layout/king-layout.vue')['default']
    LanguageToggle: typeof import('./../../../src/components/widgets/language-toggle.vue')['default']
    LayoutContent: typeof import('./../../../src/components/king-layout/components/layout-content.vue')['default']
    LayoutFooter: typeof import('./../../../src/components/king-layout/components/layout-footer.vue')['default']
    LayoutHeader: typeof import('./../../../src/components/king-layout/components/layout-header.vue')['default']
    LayoutSidebar: typeof import('./../../../src/components/king-layout/components/layout-sidebar.vue')['default']
    LayoutTabbar: typeof import('./../../../src/components/king-layout/components/layout-tabbar.vue')['default']
    Menu: typeof import('./../../../src/components/king-menu/components/menu.vue')['default']
    MenuContent: typeof import('./../../../src/components/king-menu/components/menu-content.vue')['default']
    MenuItem: typeof import('./../../../src/components/king-menu/components/menu-item.vue')['default']
    MenuView: typeof import('./../../../src/components/king-menu/menu-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCollapseButton: typeof import('./../../../src/components/king-layout/components/widgets/sidebar-collapse-button.vue')['default']
    SidebarFixedButton: typeof import('./../../../src/components/king-layout/components/widgets/sidebar-fixed-button.vue')['default']
    SubMenu: typeof import('./../../../src/components/king-menu/components/sub-menu.vue')['default']
    SubMenuUi: typeof import('./../../../src/components/king-menu/sub-menu-ui.vue')['default']
    ThemeToggle: typeof import('./../../../src/components/widgets/theme-toggle.vue')['default']
  }
}
