/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElLink: typeof import('element-plus/es')['ElLink']
    Form: typeof import('./../../components/king-form/form-render/form.vue')['default']
    FormField: typeof import('./../../components/king-form/form-render/form-field.vue')['default']
    FormLabel: typeof import('./../../components/king-form/form-render/form-label.vue')['default']
    FormMessage: typeof import('./../../components/king-form/form-render/form-message.vue')['default']
    LanguageToggle: typeof import('./../../components/toggle/language-toggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./../../components/toggle/theme-toggle.vue')['default']
  }
}
