/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FieldComponents: typeof import('./../../components/king-form/form-render/field-components.vue')['default']
    Form: typeof import('./../../components/king-form/form-render/form.vue')['default']
    FormApi: typeof import('./../../components/king-form/form-api.vue')['default']
    FormField: typeof import('./../../components/king-form/form-render/form-field.vue')['default']
    FormFiled: typeof import('./../../components/king-form/form-render/form-filed.vue')['default']
    FormLabel: typeof import('./../../components/king-form/form-render/form-label.vue')['default']
    IconButton: typeof import('./../../baseui/svg-icon/icon-button.vue')['default']
    Input: typeof import('./../../components/ep/Input.vue')['default']
    InputPassword: typeof import('./../../baseui/input-password/input-password.vue')['default']
    KingForm: typeof import('./../../components/king-form/king-form.vue')['default']
    KingUseForm: typeof import('./../../components/king-form/king-use-form.vue')['default']
    LanguageToggle: typeof import('./../../components/toggle/language-toggle.vue')['default']
    Option: typeof import('./../../baseui/ep/option.vue')['default']
    PasswordStrength: typeof import('./../../baseui/input-password/password-strength.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../../baseui/ep/select.vue')['default']
    SliderCaptcha: typeof import('./../../baseui/captcha/slider-captcha/index.vue')['default']
    SliderCaptchaAction: typeof import('./../../baseui/captcha/slider-captcha/slider-captcha-action.vue')['default']
    SliderCaptchaBar: typeof import('./../../baseui/captcha/slider-captcha/slider-captcha-bar.vue')['default']
    SliderCaptchaContent: typeof import('./../../baseui/captcha/slider-captcha/slider-captcha-content.vue')['default']
    SpineText: typeof import('./../../baseui/spine-text/spine-text.vue')['default']
    SvgIcon: typeof import('./../../baseui/svg-icon/svg-icon.vue')['default']
    ThemeToggle: typeof import('./../../components/toggle/theme-toggle.vue')['default']
  }
}
