#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo Start running commit-msg hook...

# Check whether the git commit information is standardized
pnpm run commitlint

echo Run commit-msg hook done.



